---
title: "The Lyrics of Beatles"
author: "juby"
date: "8/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

喜欢的乐队，听得久了，有时也会感到腻烦，但有一个例外，那就是披头士。可能是喜欢的披头士的歌太多，不论何时，总有一首能浸入心间。

披头士的歌，自己常听的大约有100多首，常听的专辑有「Love」「1」「The Beatles」「Sgt. Pepper's Lonely Hearts Club Band」「Abbey Road」和「Let It Be」这几张。至于他们到底写过多少首歌，我以前从未深究过这个问题，这日闲来无事查了一下，也并没有明确的说法。[The Beatles Bible](https://www.beatlesbible.com/songs/)总结了所有披头士录制过的歌曲，包括原创、翻唱等，共有322首。在原创歌曲的统计上，[UCR](https://ultimateclassicrock.com/every-beatles-song/)网站的一篇文章说有227首，[Vulture](https://www.vulture.com/2017/06/all-213-beatles-songs-ranked-from-worst-to-best.html)网站的文章则说有213首，Quora上有用户总结出了185首。我将[wikipedia](https://en.wikipedia.org/wiki/List_of_songs_recorded_by_the_Beatles)上的数据进行整理后，发现披头士的原创歌曲有187首，其中不包含一些未发表和未完成的歌。虽然还是不能断定具体的数字，但可以说披头士至少写了187首歌。在总结了披头士的原创歌曲后，我对这些歌的歌词作了以下简单的分析。

以下是我整理披头士歌曲和歌词的过程，使用的语言是R，虽然已经学了几个月的R了，代码还是很混乱。

在本文的分析中，使用的包主要有以下几个：
```{r message=FALSE}
library(rvest)  # scrape web content
library(genius)  # get lyrics from genius.com
library(tidyverse) # data manipulation and plot
library(wordcloud2) # plot word cloud
```


#### 歌曲收集

```{r}

```







