---
title: "Glay Songlist"
author: "juby"
date: "8/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}
library(rvest)
library(data.table)
library(lest)
library(lubridate)
```


```{r}
url <- "https://www.glay.co.jp/discography/songlist.php"

index <- list(a = 1:4, k = 1:4, s = 1:5, t = 1:3, n = 1, 
              h = 1:6, m = 1:2, y = 1, r = 1:3, w = 1)

# function to paste url and query
paste_url <- function(x, url) {
  q <- c()
  for (i in 1:10) {
    new_url <- lapply(x[[i]], function(y) paste0(url, "?page=", y, "&select=", names(x)[i]))
    q <- c(q, new_url)
  }
  return(q)
}

glay_url <- paste_url(index, url)

# function to get web content
get_content <- function(url, node) {
  content <- url %>% 
    lapply(. %>% 
      read_html() %>% 
      html_nodes(node) %>% 
      html_text()) %>% 
    unlist()
  return(content)
}

# contents of songs
song <- get_content(glay_url, ".inner .credit h1")
info <- get_content(glay_url, ".inner .credit p")  
release <- get_content(glay_url, ".inner .spec")

glay_song <- data.table(song = song, info = info, release = release)
head(glay_song)
```


```{r}
# split info
glay_song[, c("writer", "composer", "issue") := tstrsplit(info, "\n")]

# some songs have no writer or composer information
glay_song[, `:=`(
  issue = if_else(grepl("Written|Composed", info), issue, info), 
  writer = if_else(grepl("Written", writer), writer, ""), 
  composer = if_else(grepl("Composed", composer), composer, "")
)]

# extract issue date
glay_song[, issue := ymd(regmatches(issue, gregexpr("\\d+\\.\\d+\\.\\d+", issue)))]

# extract writer
glay_song[, writer := gsub("Written by (.+)", "\\1", writer)]

# extract composer
# the contents of composers are complex
glay_song[, composer := gsub("Composed by (.+)", "\\1", composer)]
glay_song[, composer := gsub("(Arranged|GLAY|Remixed)", " \\1", composer)]
```


```{r}
# release split
# romove "著作権管理団体区分"
glay_song[, release := gsub("\n著作権管理団体区分(A|B)\n", "", release)]

# extract single
glay_song[, single := gsub("\n収録シングル\n(.+)\n\n収録アルバム\n(.+)", "\\1", release)]
glay_song[, single := if_else(grepl("\n収録アルバム\n", single), "", single)]
glay_song[, single := gsub("\n収録シングル\n", "", single)]

# extract album
glay_song[, album := gsub("\n収録シングル\n(.+)\n\n収録アルバム\n(.+)", "\\2", release)]
glay_song[, album := if_else(grepl("\n収録シングル\n", album), "", album)]
glay_song[, album := gsub("\n収録アルバム\n", "", album)]

# reorder columns
glay_song[, `:=`(info = NULL, release = NULL)]
setcolorder(glay_song, c(1, 5:6, 2:4))
# fwrite(glay_song, "tidydata/data/glay_songlist.csv")
```
